Repository kurierjs/kurier, pull requests merged in 2019-05, with the labels that each got.

#95 Custom PK support
  src/application.ts
  src/processors/knex-processor.ts
  src/processors/operation-processor.ts
  src/resource.ts
  src/types.ts
  tests/dummy/db/dev.sqlite3
  tests/dummy/src/index.ts
  tests/dummy/src/resources/article.ts
  tests/dummy/src/resources/comment.ts
  tests/dummy/src/resources/user.ts
  tests/dummy/src/resources/vote.ts
Labels: enhancement

#103 support requests with no relationships attribute
  src/application.ts
Labels: bug

#106 Adds support for WebSocket authentication
  src/application-instance.ts
  src/json-api-errors.ts
  src/middlewares/json-api-koa.ts
  src/middlewares/json-api-websocket.ts
Labels: enhancement

#109 Authentication/Authorization fixes
  src/application-instance.ts
  src/application.ts
  src/decorators/authorize.ts
  src/processors/knex-processor.ts
  tests/dummy/db/dev.sqlite3
  tests/dummy/src/index.ts
  tests/dummy/src/processors/session.ts
  tests/dummy/src/processors/user.ts
  tests/dummy/src/processors/vote.ts
  tests/dummy/src/resources/Session.ts
  tests/dummy/src/resources/vote.ts
  tests/dummy/src/utils/hash.ts
  tests/dummy/src/utils/sign-and-timestamp.ts
  tsconfig.json
Labels: bug

#128 Removes default user permissions
  src/processors/user-processor.ts
Labels: bug, discussion

#136 Fix sort clause
  src/processors/knex-processor.ts
  src/processors/operation-processor.ts
  tests/dummy/db/dev.sqlite3
  tests/dummy/src/resources/article.ts
Labels: bug

#142 fix & refactor: empty/not-found responses
  src/application.ts
  src/processors/knex-processor.ts
  src/serializers/serializer.ts
  src/types.ts
Labels: bug

#144 fix: GET /:id should return an object not an array
  src/application-instance.ts
  src/application.ts
  src/processors/knex-processor.ts
  src/processors/operation-processor.ts
  src/processors/user-processor.ts
  src/serializers/serializer.ts
  tests/acceptance/helpers/create-session-token.ts
  tests/acceptance/helpers/create-user.ts
Labels: bug

#154 fix: sets the user relationship FK name
  src/addons/user-management.ts
  src/processors/session-processor.ts
Labels: bug

#159 add ws authorization
  README.md
Labels: documentation

#153 Documentation: describes the UserManagement addon
  README.md
Labels: documentation

#152 Documentation: describes the addon system
  README.md
Labels: documentation

#151 Documentation: adds info about bulk operations and using jsonApiWebSocket
  README.md
Labels: documentation

#158 add custom primary key, and relationships
  README.md
Labels: documentation

#160 Documentation: Adds `Serialization` section
  README.md
Labels: documentation

#161 Fix has many relationships default fk
  README.md
  src/processors/knex-processor.ts
  tests/dummy/src/processors/user.ts
  tests/dummy/src/resources/user.ts
Labels: bug

#162 Documentation: computed properties
  README.md
  tests/dummy/src/processors/article.ts
Labels: documentation

#169 Adds UserProcessor scope for role/permission providers
  src/application-instance.ts
  src/types.ts
  tests/dummy/src/app.ts
Labels: bug

#174 fix sql connection block by transaction
  src/application-instance.ts
Labels: bug

#172 Documentation: Roles and permissions
  README.md
Labels: documentation

#189 More tests!
  tests/data/migrations/20190506190058_add_articles_table.ts
  tests/data/migrations/20190523003617_add_votes_table.ts
  tests/data/migrations/20190527003617_add_comments_table.ts
  tests/data/seeds/seed.ts
  tests/test-suite/acceptance/article.test.ts
  tests/test-suite/acceptance/comment.test.ts
  tests/test-suite/acceptance/factories/article.ts
  tests/test-suite/acceptance/factories/comment.ts
  tests/test-suite/acceptance/factories/user.ts
  tests/test-suite/acceptance/user.test.ts
  tests/test-suite/test-app/resources/user.ts
Labels: testing

#192 Implements a better serialization method for included resources
  package.json
  src/application.ts
  src/serializers/serializer.ts
  src/types.ts
Labels: enhancement

#196 fixes pagination test
  tests/test-suite/acceptance/comment.test.ts
Labels: bug, testing

#198 Test Suite optimizations
  package.json
  tests/data/knexfile.ts
  tests/data/seeds/seed.ts
  tests/test-suite/acceptance/user.test.ts
  tests/test-suite/globalSetup.ts
  tests/test-suite/setup.ts
Labels: testing
