Repository kurierjs/kurier, pull requests merged in 2019-04, with the labels that each got.

#67 Adds documentation
  README.md
  docs/data-flow.svg
Labels: discussion

#74 fixes documentation errors
  README.md
Labels: documentation

#84 Fixes documentation
  README.md
Labels: documentation

#83 Fix custom named relationships, Fix Has Many includes
  src/processors/knex-processor.ts
  tests/dummy/db/dev.sqlite3
  tests/dummy/src/index.ts
  tests/dummy/src/resources/comment.ts
  tests/dummy/src/resources/user.ts
Labels: bug

#88 Fix columns named "type"
  src/application.ts
  tests/dummy/db/dev.sqlite3
  tests/dummy/src/resources/comment.ts
Labels: bug

#93 adds resource deserializer to requests
  src/application.ts
Labels: enhancement

#97 Resource serializer fix
  src/application.ts
Labels: bug
