Repository kurierjs/kurier, pull requests merged in 2020-10, with the labels that each got.

#238 Adds tests for Knex-less operations
  tests/test-suite/acceptance/random.test.ts
  tests/test-suite/test-app/app.ts
  tests/test-suite/test-app/processors/random.ts
  tests/test-suite/test-app/resources/random.ts
Labels: testing

#227 Includes nested relationships as part of main resource's relationships
  src/processors/knex-processor.ts
  src/serializers/serializer.ts
  src/types.ts
Labels: enhancement

#242 Add support for Node 14, Update most of the dependencies
  .github/workflows/nodejs.yml
  package.json
  yarn.lock
Labels: dependencies

#244 fix nested included resources tests
  tests/test-suite/acceptance/factories/nestedResources.ts
Labels: testing
