Repository kurierjs/kurier, pull requests merged in 2020-02, with the labels that each got.

#223 Knex and Test Dependencies Update
  package.json
  tests/data/camelCase/migrations/20190506190057_add_users_table.ts
  tests/data/camelCase/migrations/20190506190058_add_articles_table.ts
  tests/data/camelCase/migrations/20190523003617_add_votes_table.ts
  tests/data/camelCase/migrations/20190527003617_add_comments_table.ts
  tests/data/knexfile.ts
  tests/data/snake_case/migrations/20190506190057_add_users_table.ts
  tests/data/snake_case/migrations/20190506190058_add_articles_table.ts
  tests/data/snake_case/migrations/20190523003617_add_votes_table.ts
  tests/data/snake_case/migrations/20190527003617_add_comments_table.ts
  tests/data/snake_case/seeds/seed.ts
  yarn.lock
Labels: dependencies, testing

#224 Refactor - Settings File Cleanup, Updated Docs, Updated TSConfig Files
  .circleci/config.yml
  .vscode/launch.json
  .vscode/settings.json
  README.md
  docs/index.md
  tsconfig.dummy.json
  tsconfig.test.json
Labels: documentation, enhancement, refactor

#219 Relationship Endpoints / Nested Includes
  package.json
  src/application.ts
  src/middlewares/json-api-koa.ts
  src/processors/knex-processor.ts
  src/processors/operation-processor.ts
  src/processors/relationship-processor.ts
  src/serializers/serializer.ts
  src/utils/http-utils.ts
  tests/dummy-app/app.ts
  tests/dummy-app/processors/article.ts
  tests/test-suite/acceptance/factories/nested.ts
  tests/test-suite/acceptance/factories/utils.ts
  tests/test-suite/acceptance/factories/vote.ts
  tests/test-suite/acceptance/nestedResources.test.ts
  tests/test-suite/test-app/app.ts
  tests/test-suite/test-app/processors/user.ts
  tests/test-suite/test-app/resources/user.ts
  tsconfig.dummy.json
Labels: enhancement, refactor

#180 Describes filtering syntax for JSONAPI-TS
  profiles/filtering.md
Labels: discussion

#230 Readme Redirection and RTD improvements
  README.md
  docs/index.md
Labels: documentation
